import json
import re

class DataEthicsMufti:
    def __init__(self):
        self.rules_database = {
            'privacy': {
                'rule': 'No Harm Principle',
                'principle': 'No one should harm others privacy',
                'sources': ['Hadith of No Harm', 'Rule of Ownership'],
                'applications': ['personal data', 'surveillance', 'tracking']
            },
            'ownership': {
                'rule': 'Principle of Innocence and Respect for Ownership',
                'principle': 'Individuals data belongs to them unless proven otherwise',
                'sources': ['Rule of Ownership', 'Principle of Innocence'],
                'applications': ['data selling', 'data sharing', 'commercial use']
            },
            'consent': {
                'rule': 'Matters are Judged by Intentions',
                'principle': 'Data usage requires informed consent',
                'sources': ['Hadith of Intentions', 'Rule of Justice'],
                'applications': ['data collection', 'data processing', 'data analysis']
            }
        }
        
        self.keywords = {
            'privacy': ['privacy', 'private', 'confidential', 'personal'],
            'ownership': ['ownership', 'sell', 'buy', 'owner', 'belong'],
            'consent': ['consent', 'permission', 'agreement', 'consent form']
        }
    
    def analyze_question(self, question):
        question_lower = question.lower()
        
        for category, keywords in self.keywords.items():
            for keyword in keywords:
                if keyword in question_lower:
                    return category, self.rules_database[category]
        
        return 'general', {'rule': 'Seek guidance and consult with experts'}
    
    def generate_fatwa(self, question):
        category, ruling = self.analyze_question(question)
        
        fatwa = f"""
        Question: {question}
        
        Ruling: {ruling['rule']}
        Jurisprudential Principle: {ruling.get('principle', 'Consult with expert')}
        Sources: {', '.join(ruling.get('sources', []))}
        
        Explanation: Based on {ruling['rule']}, {ruling.get('principle', 'Precaution is recommended')}
        """
        
        return fatwa

# Usage
mufti = DataEthicsMufti()

questions = [
    "Is selling patient health data permissible?",
    "What is the ruling on using personal data without user consent?",
    "Who owns data generated by artificial intelligence?"
]

for question in questions:
    print(mufti.generate_fatwa(question))
    print("="*60)